services:
 nginx:
  build: ./requirements/nginx/
  image: nginx
  container_name: nginx
  depends_on:
   - base_img
   - wordpress
  ports: 
   - "443:443"
  networks:
   - inc_net
  volumes:
   - "wordpress_vol:/var/www/html/"
  restart: on-failure
  env_file:
   - .env

 mariadb:
  build: ./requirements/mariadb/
  image: mariadb
  container_name: mariadb
  depends_on:
   - base_img
  networks:
   - inc_net
  volumes:
   - "data_base_vol:/var/lib/mysql/"
  restart: on-failure
  env_file:
   - .env

 wordpress:
  build: ./requirements/wordpress/
  image: wordpress
  container_name: wordpress
  depends_on:
   - base_img
   - mariadb
  networks:
   - inc_net
  volumes:
   - "wordpress_vol:/var/www/html/"
  restart: on-failure
  env_file:
   - .env

 base_img:
  build: ./requirements/tools/
  image: srcs-base_img

volumes:
 wordpress_vol:
  driver: local
  driver_opts:
   type: none
   device: /home/samusanc/data/wordpress
   o: bind

 data_base_vol:
  driver: local
  driver_opts:
   type: none
   device: /home/samusanc/data/db
   o: bind

networks:
 inc_net:
